### ISSUE TITLE
Fiscal Code not working

### ISSUE THREAD

**Issue by kerby82** [topac/codice_fiscale#3]
I'm using the gem but it does not work. It works just with the example provided in the homepage.

If I use other values like below:
2.1.8 :100 > CodiceFiscale.calculate(
2.1.8 :101 >         :name          => 'Mario',
2.1.8 :102 >         :surname       => 'Rossi',
2.1.8 :103 >         :gender        => :male,
2.1.8 :104 >         :birthdate     => Date.new(1987, 1, 1),
2.1.8 :105 >         :province_code => 'RM',
2.1.8 :106 >         :city_name     => 'Roma'
2.1.8 :107?>     )
 => "XXXXXX87A01H501J"

It does not work.

**Comment by topac** [comment]
Hi, be sure to use the correct gem, the gem name is with the _dash_: **codice-fiscale**, not with the _underscore_ (**codice_fiscale**). So the right command to install the gem is 

> gem install codice-fiscale

**Comment by giamma13** [comment]
BTW I am also getting the same XXXXX code

```
[6] pry(main)> CodiceFiscale.calculate( 
[6] pry(main)*   :name          => 'Mario',    
[6] pry(main)*   :surname       => 'Rossi',     
[6] pry(main)*   :gender        => :male,    
[6] pry(main)*   :birthdate     => Date.new(1987, 1, 1),    
[6] pry(main)*   :province_code => 'LC',     
[6] pry(main)*   :city_name     => 'Abbadia Lariana'    
[6] pry(main)* )    
=> "XXXXXX87A01A005D"
```

please advise on how to fix it

**Comment by giamma13** [comment]
sorry created a new issue
- Calculate gives wrong results #5
